[tools]
node = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"pipx:gitingest" = "latest"
python = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby", "python"]

[settings.pipx]
uvx = true
