[tools]
actionlint = "latest"
bun = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:diff2html-cli" = "latest"
"npm:textlint" = "latest"
"npm:vercel" = "latest"
"pipx:gitingest" = "latest"
"pipx:jupytext" = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby", "python"]

[settings.pipx]
uvx = true
